<a href="https://colab.research.google.com/github/brajesh995/231FA04C59_MLOPS/blob/main/MLLab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## a. Load a dataset and perform preprocessing

In [3]:
# Load the dataset
df = pd.read_csv('/content/cse_industry_skill_gap_1500.csv')
display(df.head())

,Skill_ID,Skill_Name,Skill_Category,Curriculum_Coverage_Score,Theory_Lecture_Hours,Lab_Practical_Hours,Curriculum_Age_Years,Assessment_Frequency,Faculty_Proficiency_Rating,Industry_Demand_Score,...,Industry_Certified_Curriculum,Internship_Requirement_Flag,Hands_On_Lab_Ratio,Expert_Importance_Score,Alumni_Satisfaction_Score,Employer_Satisfaction_Score,Skill_Recency_Score,Lab_Infrastructure_Budget_k,Student_Enrollment_Count,Gap_Status
0,SKILL-1000,Flutter - Level 2,Web & Mobile,4.75,71,20,7,9,1.62,0.29,...,1,1,0.22,4.75,1.00,4.97,0.8,63.66,363,Aligned
1,SKILL-1001,Deep Learning - Level 3,AI & Data Science,0.12,58,41,8,2,2.53,4.92,...,1,0,0.41,4.86,4.23,2.22,0.2,14.28,389,Gap
2,SKILL-1002,GraphQL - Level 2,Software Engineering,2.48,46,34,6,0,2.04,3.31,...,1,1,0.42,2.80,2.58,4.71,1.4,74.09,320,Gap
3,SKILL-1003,Flutter - Level 3,Web & Mobile,0.23,39,20,8,1,3.16,2.93,...,0,0,0.34,4.95,4.09,1.79,0.2,5.52,188,Gap
4,SKILL-1004,Operating Systems - Level 3,Core Computer Science,3.95,4,41,7,9,1.46,4.32,...,0,0,0.91,3.37,2.10,3.24,0.8,41.38,511,Aligned

### 1. Handle missing values

First, let's check for any missing values in the dataset.

In [11]:
missing_values = df.isnull().sum()
print("Missing values in each column:")
print(missing_values[missing_values > 0])

if missing_values.sum() == 0:
    print("No missing values found. Proceeding without imputation.")
else:
    print("Missing values detected. Further handling might be required if any columns have missing values.")

Missing values in each column:
Series([], dtype: int64)
No missing values found. Proceeding without imputation.

### 2. Encode categorical variables

In [12]:
from sklearn.preprocessing import OneHotEncoder

# Identify categorical and numerical columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()

# Exclude 'Skill_ID', 'Skill_Name' as they are identifiers
# Also exclude 'Gap_Status' as it's our target variable and will be handled separately
categorical_features_to_encode = [col for col in categorical_cols if col not in ['Skill_ID', 'Skill_Name', 'Gap_Status']]

# Apply One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=categorical_features_to_encode, drop_first=True)

display(df_encoded.head())

,Skill_ID,Skill_Name,Curriculum_Coverage_Score,Theory_Lecture_Hours,Lab_Practical_Hours,Curriculum_Age_Years,Assessment_Frequency,Faculty_Proficiency_Rating,Industry_Demand_Score,Job_Posting_Count_k,...,Skill_Recency_Score,Lab_Infrastructure_Budget_k,Student_Enrollment_Count,Gap_Status,Skill_Category_Cloud Platforms,Skill_Category_Core Computer Science,Skill_Category_DevOps & Infrastructure,Skill_Category_Security & Risk,Skill_Category_Software Engineering,Skill_Category_Web & Mobile
0,SKILL-1000,Flutter - Level 2,4.75,71,20,7,9,1.62,0.29,55.28,...,0.8,63.66,363,Aligned,False,False,False,False,False,True
1,SKILL-1001,Deep Learning - Level 3,0.12,58,41,8,2,2.53,4.92,20.72,...,0.2,14.28,389,Gap,False,False,False,False,False,False
2,SKILL-1002,GraphQL - Level 2,2.48,46,34,6,0,2.04,3.31,14.34,...,1.4,74.09,320,Gap,False,False,False,False,True,False
3,SKILL-1003,Flutter - Level 3,0.23,39,20,8,1,3.16,2.93,88.99,...,0.2,5.52,188,Gap,False,False,False,False,False,True
4,SKILL-1004,Operating Systems - Level 3,3.95,4,41,7,9,1.46,4.32,29.41,...,0.8,41.38,511,Aligned,False,True,False,False,False,False

### 3. Normalize/scale data

In [13]:
from sklearn.preprocessing import StandardScaler

# Identify numerical columns for scaling
numerical_cols = df_encoded.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Exclude 'Gap_Status' if it's in numerical columns, as it's the target
numerical_features_to_scale = [col for col in numerical_cols if col != 'Gap_Status']

# Initialize StandardScaler
scaler = StandardScaler()

# Apply scaling to numerical features
df_scaled = df_encoded.copy()
df_scaled[numerical_features_to_scale] = scaler.fit_transform(df_scaled[numerical_features_to_scale])

display(df_scaled.head())

,Skill_ID,Skill_Name,Curriculum_Coverage_Score,Theory_Lecture_Hours,Lab_Practical_Hours,Curriculum_Age_Years,Assessment_Frequency,Faculty_Proficiency_Rating,Industry_Demand_Score,Job_Posting_Count_k,...,Skill_Recency_Score,Lab_Infrastructure_Budget_k,Student_Enrollment_Count,Gap_Status,Skill_Category_Cloud Platforms,Skill_Category_Core Computer Science,Skill_Category_DevOps & Infrastructure,Skill_Category_Security & Risk,Skill_Category_Software Engineering,Skill_Category_Web & Mobile
0,SKILL-1000,Flutter - Level 2,1.561267,1.565869,-0.567569,1.099316,1.601895,-1.194287,-1.495204,0.978128,...,-1.099316,0.409722,0.237343,Aligned,False,False,False,False,False,True
1,SKILL-1001,Deep Learning - Level 3,-1.660371,0.960879,0.650390,1.536594,-0.837185,-0.403161,1.714648,-0.363979,...,-1.536594,-1.369027,0.401566,Gap,False,False,False,False,False,False
2,SKILL-1002,GraphQL - Level 2,-0.018240,0.402427,0.244404,0.662038,-1.534065,-0.829152,0.598479,-0.611740,...,-0.662038,0.785428,-0.034255,Gap,False,False,False,False,True,False
3,SKILL-1003,Flutter - Level 3,-1.583831,0.076663,-0.567569,1.536594,-1.185625,0.144541,0.335035,2.287225,...,-1.536594,-1.684576,-0.867999,Gap,False,False,False,False,False,True
4,SKILL-1004,Operating Systems - Level 3,1.004613,-1.552156,0.650390,1.099316,1.601895,-1.333386,1.298684,-0.026510,...,-1.099316,-0.392840,1.172148,Aligned,False,True,False,False,False,False

### 4. Split dataset into training and testing sets

In [14]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df_scaled.drop(['Skill_ID', 'Skill_Name', 'Gap_Status'], axis=1)
y = df_scaled['Gap_Status']

# Convert target to numerical if it's not already (e.g., 'Aligned' to 0, 'Gap' to 1)
if y.dtype == 'object' or y.dtype == 'bool':
    y = y.astype('category').cat.codes


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (1200, 28)
X_test shape: (300, 28)
y_train shape: (1200,)
y_test shape: (300,)

### 5. Automate preprocessing steps using a pipeline

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# Re-define categorical and numerical features from the original DataFrame
numerical_features = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = df.select_dtypes(include=['object', 'category']).columns.tolist()

# Exclude 'Skill_ID', 'Skill_Name' from features
numerical_features = [col for col in numerical_features if col not in ['Gap_Status']]
categorical_features = [col for col in categorical_features if col not in ['Skill_ID', 'Skill_Name', 'Gap_Status']]

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore', drop='first'))
])

# Create a column transformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ],
    remainder='passthrough' # Keep other columns (like Skill_ID, Skill_Name if not dropped)
)

# Create a dummy pipeline to demonstrate the preprocessor
# In a real scenario, a model would follow `preprocessor`
pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

# Fit and transform the original data (excluding identifiers and target for X)
X_pipeline = df.drop(['Skill_ID', 'Skill_Name', 'Gap_Status'], axis=1)
y_pipeline = df['Gap_Status'].astype('category').cat.codes

X_processed_pipeline = pipeline.fit_transform(X_pipeline)

print("Shape of processed data using pipeline:", X_processed_pipeline.shape)
print("First 5 rows of processed data (array format):")
print(X_processed_pipeline[:5])

Shape of processed data using pipeline: (1500, 28)
First 5 rows of processed data (array format):
[[ 1.56126747  1.56586936 -0.56756855  1.09931605  1.60189465 -1.19428662
  -1.49520393  0.97812774  1.56793877  0.75539176  0.97888944 -1.68021177
   0.98412598  0.98938962  0.99600797 -0.96189648  1.50611177 -1.74653598
   1.71726321 -1.09931605  0.4097222   0.23734344  0.          0.
   0.          0.          0.          1.        ]
 [-1.66037053  0.96087932  0.65038971  1.53659371 -0.83718508 -0.40316106
   1.71464778 -0.36397884  0.40852037  0.82088209  0.97888944 -0.18192562
   0.98412598  0.98938962 -1.00400803 -0.17789872  1.60379283  1.0556532
  -0.66614737 -1.53659371 -1.36902665  0.40156582  0.          0.
   0.          0.          0.          0.        ]
 [-0.01823971  0.40242697  0.24440362  0.66203838 -1.534065   -0.82915175
   0.59847905 -0.61174041  2.76477385  1.18241545  0.97888944 -1.10528801
  -1.01613007  0.98938962  0.99600797 -0.13663568 -0.2255071  -0.37580567
   1.49192257 -0.66203838  0.78542796 -0.0342551   0.          0.
   0.          0.          1.          0.        ]
 [-1.58383053  0.0766631  -0.56756855  1.53659371 -1.18562504  0.14454125
   0.33503549  2.28722533 -1.51419843  0.70928122  0.97888944 -0.71329454
  -1.01613007 -1.01072417 -1.00400803 -0.46674     1.6837137   0.93419608
  -1.03882611 -1.53659371 -1.68457626 -0.86799947  0.          0.
   0.          0.          0.          1.        ]
 [ 1.00461296 -1.55215625  0.65038971  1.09931605  1.60189465 -1.33338562
   1.29868428 -0.02651049 -0.48548899 -0.19956419 -1.02156582 -0.66973971
   0.98412598 -1.01072417 -1.00400803  1.88525329  0.28065842 -0.79223007
   0.21788128 -1.09931605 -0.39284006  1.17214773  0.          1.
   0.          0.          0.          0.        ]]

### 6. Save processed dataset for reuse

In [16]:
import numpy as np

# Get feature names after one-hot encoding for the pipeline output
# This part can be tricky as ColumnTransformer doesn't directly return DataFrame with names
# For simplicity, we'll recreate feature names manually for demonstration

# First, get the feature names from the one-hot encoder
# Fit the preprocessor first if not already done
pipeline.fit(X_pipeline)

onehot_feature_names = pipeline.named_steps['preprocessor'].named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(categorical_features)

# Combine numerical feature names and one-hot encoded feature names
all_processed_features = numerical_features.copy()
all_processed_features.extend(onehot_feature_names)

# Convert the processed sparse matrix (if any) or array to a DataFrame
# Handle potential sparse output from OneHotEncoder
if isinstance(X_processed_pipeline, np.ndarray):
    processed_df = pd.DataFrame(X_processed_pipeline, columns=all_processed_features)
else:
    processed_df = pd.DataFrame(X_processed_pipeline.toarray(), columns=all_processed_features)

# Add the target variable back (assuming it was encoded similarly as y_pipeline)
processed_df['Gap_Status'] = y_pipeline.values

# Save to a new CSV file
output_filename = 'cse_industry_skill_gap_1500_processed.csv'
processed_df.to_csv(output_filename, index=False)
print(f"Processed dataset saved to '{output_filename}'")
display(processed_df.head())

Processed dataset saved to 'cse_industry_skill_gap_1500_processed.csv'

,Curriculum_Coverage_Score,Theory_Lecture_Hours,Lab_Practical_Hours,Curriculum_Age_Years,Assessment_Frequency,Faculty_Proficiency_Rating,Industry_Demand_Score,Job_Posting_Count_k,Avg_Entry_Salary_USD_k,Market_Growth_Rate_Pct,...,Skill_Recency_Score,Lab_Infrastructure_Budget_k,Student_Enrollment_Count,Skill_Category_Cloud Platforms,Skill_Category_Core Computer Science,Skill_Category_DevOps & Infrastructure,Skill_Category_Security & Risk,Skill_Category_Software Engineering,Skill_Category_Web & Mobile,Gap_Status
0,1.561267,1.565869,-0.567569,1.099316,1.601895,-1.194287,-1.495204,0.978128,1.567939,0.755392,...,-1.099316,0.409722,0.237343,0.0,0.0,0.0,0.0,0.0,1.0,0
1,-1.660371,0.960879,0.650390,1.536594,-0.837185,-0.403161,1.714648,-0.363979,0.408520,0.820882,...,-1.536594,-1.369027,0.401566,0.0,0.0,0.0,0.0,0.0,0.0,1
2,-0.018240,0.402427,0.244404,0.662038,-1.534065,-0.829152,0.598479,-0.611740,2.764774,1.182415,...,-0.662038,0.785428,-0.034255,0.0,0.0,0.0,0.0,1.0,0.0,1
3,-1.583831,0.076663,-0.567569,1.536594,-1.185625,0.144541,0.335035,2.287225,-1.514198,0.709281,...,-1.536594,-1.684576,-0.867999,0.0,0.0,0.0,0.0,0.0,1.0,1
4,1.004613,-1.552156,0.650390,1.099316,1.601895,-1.333386,1.298684,-0.026510,-0.485489,-0.199564,...,-1.099316,-0.392840,1.172148,0.0,1.0,0.0,0.0,0.0,0.0,0

### 7. Compare results before and after preprocessing

In [17]:
print("\n--- Original DataFrame Info ---")
df.info()
print("\nOriginal DataFrame Head:")
display(df.head())

print("\n--- Processed DataFrame Info (from pipeline) ---")
processed_df.info()
print("\nProcessed DataFrame Head:")
display(processed_df.head())

print("\nComparison of Shapes:")
print(f"Original df shape: {df.shape}")
print(f"Processed df shape: {processed_df.shape}")

print("\nComparison of Data Types (Original vs. Processed):")
print("Original dtypes:\n", df.dtypes.value_counts())
print("Processed dtypes:\n", processed_df.dtypes.value_counts())

--- Original DataFrame Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Skill_ID                       1500 non-null   object
 1   Skill_Name                     1500 non-null   object
 2   Skill_Category                 1500 non-null   object
 3   Curriculum_Coverage_Score      1500 non-null   float64
 4   Theory_Lecture_Hours           1500 non-null   int64
 5   Lab_Practical_Hours            1500 non-null   int64
 6   Curriculum_Age_Years           1500 non-null   int64
 7   Assessment_Frequency           1500 non-null   int64
 8   Faculty_Proficiency_Rating     1500 non-null   float64
 9   Industry_Demand_Score          1500 non-null   float64
 10  Job_Posting_Count_k            1500 non-null   float64
 11  Avg_Entry_Salary_USD_k         1500 non-null   float64
 12  Market_Growth_Rate_Pct         1500 non-null   float64
 13  Emerging_Tech_Flag             1500 non-null   int64
 14  Top_Company_Hiring_Intensity   1500 non-null   float64
 15  Has_Capstone_Integration       1500 non-null   int64
 16  Industry_Certified_Curriculum  1500 non-null   int64
 17  Internship_Requirement_Flag    1500 non-null   int64
 18  Hands_On_Lab_Ratio             1500 non-null   float64
 19  Expert_Importance_Score        1500 non-null   float64
 20  Alumni_Satisfaction_Score      1500 non-null   float64
 21  Employer_Satisfaction_Score    1500 non-null   float64
 22  Skill_Recency_Score            1500 non-null   float64
 23  Lab_Infrastructure_Budget_k    1500 non-null   float64
 24  Student_Enrollment_Count       1500 non-null   int64
 25  Gap_Status                     1500 non-null   object
dtypes: float64(13), int64(9), object(4)
memory usage: 304.8+ KB

Original DataFrame Head:

,Skill_ID,Skill_Name,Skill_Category,Curriculum_Coverage_Score,Theory_Lecture_Hours,Lab_Practical_Hours,Curriculum_Age_Years,Assessment_Frequency,Faculty_Proficiency_Rating,Industry_Demand_Score,...,Industry_Certified_Curriculum,Internship_Requirement_Flag,Hands_On_Lab_Ratio,Expert_Importance_Score,Alumni_Satisfaction_Score,Employer_Satisfaction_Score,Skill_Recency_Score,Lab_Infrastructure_Budget_k,Student_Enrollment_Count,Gap_Status
0,SKILL-1000,Flutter - Level 2,Web & Mobile,4.75,71,20,7,9,1.62,0.29,...,1,1,0.22,4.75,1.00,4.97,0.8,63.66,363,Aligned
1,SKILL-1001,Deep Learning - Level 3,AI & Data Science,0.12,58,41,8,2,2.53,4.92,...,1,0,0.41,4.86,4.23,2.22,0.2,14.28,389,Gap
2,SKILL-1002,GraphQL - Level 2,Software Engineering,2.48,46,34,6,0,2.04,3.31,...,1,1,0.42,2.80,2.58,4.71,1.4,74.09,320,Gap
3,SKILL-1003,Flutter - Level 3,Web & Mobile,0.23,39,20,8,1,3.16,2.93,...,0,0,0.34,4.95,4.09,1.79,0.2,5.52,188,Gap
4,SKILL-1004,Operating Systems - Level 3,Core Computer Science,3.95,4,41,7,9,1.46,4.32,...,0,0,0.91,3.37,2.10,3.24,0.8,41.38,511,Aligned

--- Processed DataFrame Info (from pipeline) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 29 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Curriculum_Coverage_Score               1500 non-null   float64
 1   Theory_Lecture_Hours                    1500 non-null   float64
 2   Lab_Practical_Hours                     1500 non-null   float64
 3   Curriculum_Age_Years                    1500 non-null   float64
 4   Assessment_Frequency                    1500 non-null   float64
 5   Faculty_Proficiency_Rating              1500 non-null   float64
 6   Industry_Demand_Score                   1500 non-null   float64
 7   Job_Posting_Count_k                     1500 non-null   float64
 8   Avg_Entry_Salary_USD_k                  1500 non-null   float64
 9   Market_Growth_Rate_Pct                  1500 non-null   float64
 10  Emerging_Tech_Flag                      1500 non-null   float64
 11  Top_Company_Hiring_Intensity            1500 non-null   float64
 12  Has_Capstone_Integration                1500 non-null   float64
 13  Industry_Certified_Curriculum           1500 non-null   float64
 14  Internship_Requirement_Flag             1500 non-null   float64
 15  Hands_On_Lab_Ratio                      1500 non-null   float64
 16  Expert_Importance_Score                 1500 non-null   float64
 17  Alumni_Satisfaction_Score               1500 non-null   float64
 18  Employer_Satisfaction_Score             1500 non-null   float64
 19  Skill_Recency_Score                     1500 non-null   float64
 20  Lab_Infrastructure_Budget_k             1500 non-null   float64
 21  Student_Enrollment_Count                1500 non-null   float64
 22  Skill_Category_Cloud Platforms          1500 non-null   float64
 23  Skill_Category_Core Computer Science    1500 non-null   float64
 24  Skill_Category_DevOps & Infrastructure  1500 non-null   float64
 25  Skill_Category_Security & Risk          1500 non-null   float64
 26  Skill_Category_Software Engineering     1500 non-null   float64
 27  Skill_Category_Web & Mobile             1500 non-null   float64
 28  Gap_Status                              1500 non-null   int8
dtypes: float64(28), int8(1)
memory usage: 329.7 KB

Processed DataFrame Head:

,Curriculum_Coverage_Score,Theory_Lecture_Hours,Lab_Practical_Hours,Curriculum_Age_Years,Assessment_Frequency,Faculty_Proficiency_Rating,Industry_Demand_Score,Job_Posting_Count_k,Avg_Entry_Salary_USD_k,Market_Growth_Rate_Pct,...,Skill_Recency_Score,Lab_Infrastructure_Budget_k,Student_Enrollment_Count,Skill_Category_Cloud Platforms,Skill_Category_Core Computer Science,Skill_Category_DevOps & Infrastructure,Skill_Category_Security & Risk,Skill_Category_Software Engineering,Skill_Category_Web & Mobile,Gap_Status
0,1.561267,1.565869,-0.567569,1.099316,1.601895,-1.194287,-1.495204,0.978128,1.567939,0.755392,...,-1.099316,0.409722,0.237343,0.0,0.0,0.0,0.0,0.0,1.0,0
1,-1.660371,0.960879,0.650390,1.536594,-0.837185,-0.403161,1.714648,-0.363979,0.408520,0.820882,...,-1.536594,-1.369027,0.401566,0.0,0.0,0.0,0.0,0.0,0.0,1
2,-0.018240,0.402427,0.244404,0.662038,-1.534065,-0.829152,0.598479,-0.611740,2.764774,1.182415,...,-0.662038,0.785428,-0.034255,0.0,0.0,0.0,0.0,1.0,0.0,1
3,-1.583831,0.076663,-0.567569,1.536594,-1.185625,0.144541,0.335035,2.287225,-1.514198,0.709281,...,-1.536594,-1.684576,-0.867999,0.0,0.0,0.0,0.0,0.0,1.0,1
4,1.004613,-1.552156,0.650390,1.099316,1.601895,-1.333386,1.298684,-0.026510,-0.485489,-0.199564,...,-1.099316,-0.392840,1.172148,0.0,1.0,0.0,0.0,0.0,0.0,0

Comparison of Shapes:
Original df shape: (1500, 26)
Processed df shape: (1500, 29)

Comparison of Data Types (Original vs. Processed):
Original dtypes:
 float64    13
int64       9
object      4
Name: count, dtype: int64
Processed dtypes:
 float64    28
int8        1
Name: count, dtype: int64